### ISSUE TITLE
Develop a proper UI

### ISSUE THREAD

**Issue by jdank417** [jdank417/GroceryBarcodeScanner#1]

**Comment by vagapovaaatwit** [comment]
Progress track: 
![photo_5055558261721379702_y](https://github.com/user-attachments/assets/70ebdcff-b076-4ca8-8f1a-031803239827)
![photo_5055558261721379703_y](https://github.com/user-attachments/assets/6b28ae24-ae3b-46f1-9d38-f3980b50806f)
![photo_5055558261721379699_y](https://github.com/user-attachments/assets/59e358ee-e031-4227-b1c9-9c2dea90ef7a)

**Comment by jdank417** [comment]
Great work! I look forward to trying it out when pushed!

**Comment by vagapovaaatwit** [comment]
Some progress check (3 versions). Help with images rearrangement was needed:
![photo_5073514055402106045_w](https://github.com/user-attachments/assets/bc7d2cc4-f949-4e90-b8e5-1967603bbd1e)
![photo_5094081116184358110_w](https://github.com/user-attachments/assets/cbfb9010-c985-4b8a-a4de-211b74e9d61b)
![photo_5094081116184358132_w](https://github.com/user-attachments/assets/dd192180-d08a-4fd9-bea1-cb737629f924)
![photo_5094081116184358133_w](https://github.com/user-attachments/assets/18d98937-f3c4-4ffa-be96-cb757d156c8e)

**Comment by jdank417** [comment]
Feel free to close this now, changes have been moved to master. Great work!!!
